services:
  - type: web
    name: cse-340-service-network
    env: node
    plan: free

    #root directory
    rootDir: CSE-340-COURSE-REPO 



    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
        sync: false

autoDeply: yes